name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v2

    - name: Dependencies
      run: cat packages.txt | xargs sudo apt-get install 
      
    - name: Scrape
      run: ./scrape.sh && cat uids | while read line; do ./notify.sh "$line"; done
