name: Main

on:
  schedule:
  - cron: "0 2,11 * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v2

    - name: Dependencies
      run: cat packages.txt | xargs sudo apt-get install 
      
    - name: Scrape
      run: ./scrape.sh

    - name: Notify
      run: if [ "$(cat ./update)" = "yes" ]; then cat uids | while read line; do ./notify.sh "$line"; done; fi
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"
        git add ./oldChar
        git commit -m "Update character" || echo No changes
    
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
